"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, ArrowRight, BookOpen, Building2, CalendarDays, Check, CheckCircle2, ChevronRight, CircleDashed, ClipboardList, Cloud, Clock3, Download, FileSpreadsheet, FileText, Image as ImageIcon, LoaderCircle, MapPin, Plus, Printer, RefreshCw, Search, ShieldCheck, Users, X } from "lucide-react";
import { collection, doc, getDoc, getDocs, setDoc } from "firebase/firestore";
import { db } from "@/lib/firebase/config";
import { useAuth } from "@/contexts/AuthContext";
import { deleteDocument, uploadDocument } from "@/lib/firebase/storage";
import type { FieldProject } from "@/components/field-progress/FieldProjectProfile";

type RecordType = "drawing" | "DPR" | "TBT" | "PHOTO" | "DOCUMENT";
type WorkItem = { id: string; label: string; status?: string; updatedAt?: string; drawingId: string };
type WorkspaceRecord = {
  id: string; title: string; subtitle: string; date: string; createdAt?: string; updatedAt?: string; uploadedAt?: string;
  image?: string; type: RecordType; workItems: number; complete: number; inProgress: number; openItems: number;
  items?: WorkItem[]; filePath?: string; mimeType?: string; fileName?: string; area?: string; revision?: string;
  syncPending?: boolean; manpower?: string; workers?: string; staff?: string; topic?: string; projectId?: string;
  drawingLinks?: string[]; relatedCount?: number; relatedRecords?: string[];
};
type DailyEvent = { id: string; drawingId: string; workItemId: string; action: string; status?: string; localDate?: string; timestamp?: string };
type ActivityItem = { id: string; type: RecordType; title: string; details: string; time: string; drawingId?: string; recordId?: string; photoCount?: number };

const localDay = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const recordDay = (value: string) => /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : value ? localDay(new Date(value)) : "undated";
const dateText = (date: string) => date && date !== "undated" ? new Date(/^\d{4}-\d{2}-\d{2}$/.test(date) ? `${date}T12:00:00` : date).toLocaleDateString("en-GB", { day:"2-digit", month:"short", year:"numeric" }) : "Date not set";
const monthText = (date: string) => date !== "undated" ? new Date(`${date.slice(0,7)}-01T12:00:00`).toLocaleDateString("en-GB", { month:"long", year:"numeric" }) : "Date not set";
const timeText = (value?: string) => value ? new Date(value).toLocaleTimeString("en-GB", { hour:"2-digit", minute:"2-digit" }) : "—";
const accepted = ".pdf,.jpg,.jpeg,.png,.webp";
const labels: Record<RecordType, string> = { drawing: "Drawing", DPR: "DPR", TBT: "TBT", PHOTO: "Photo", DOCUMENT: "Document" };

export function FieldWorkspaceHome({ onAddDrawing, onAddDpr, onOpenDrawing, onOpenDpr, onOpenRecord, today = false, reports = false, project, onContinueWork, onOpenProject }: { onAddDrawing: () => void; onAddDpr: () => void; onOpenDrawing: (id: string) => void; onOpenDpr: (id: string) => void; onOpenRecord?: (id: string) => void; today?: boolean; reports?: boolean; project?: FieldProject; onContinueWork?: () => void; onOpenProject?: () => void }) {
  const { user, loading } = useAuth();
  const accountUser = user && !user.isAnonymous ? user : null;
  const tbtInputRef = useRef<HTMLInputElement>(null);
  const photoInputRef = useRef<HTMLInputElement>(null);
  const documentInputRef = useRef<HTMLInputElement>(null);
  const [drawings, setDrawings] = useState<WorkspaceRecord[]>([]);
  const [documents, setDocuments] = useState<WorkspaceRecord[]>([]);
  const [events, setEvents] = useState<DailyEvent[]>([]);
  const [busy, setBusy] = useState(false);
  const [loadFailed, setLoadFailed] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [online, setOnline] = useState(true);
  const [menuOpen, setMenuOpen] = useState(false);
  const [tbtDialogOpen, setTbtDialogOpen] = useState(false);
  const [tbtDetails, setTbtDetails] = useState({ date: localDay(), area: "", topic: "", supervisor: "", manpower: "", workers: "", staff: "", remarks: "" });
  const [message, setMessage] = useState("");
  const [filter, setFilter] = useState<"all" | RecordType>("all");
  const [query, setQuery] = useState("");

  const load = useCallback(async () => {
    if (!user || user.isAnonymous) { setDrawings([]); setDocuments([]); setEvents([]); setLoadFailed(false); return; }
    setBusy(true); setLoadFailed(false); setMessage("");
    try {
      const [drawingSnapshot, documentSnapshot] = await Promise.all([
        getDocs(collection(db,"users",user.uid,"fieldDrawings")),
        getDocs(collection(db,"users",user.uid,"fieldDocuments")),
      ]);
      const drawingRows = drawingSnapshot.docs.map((snapshot) => ({ id:snapshot.id, data:snapshot.data() }));
      const nextDrawings: WorkspaceRecord[] = drawingRows.map(({id,data}) => {
        const rawItems = Array.isArray(data.workItems) ? data.workItems as Record<string, unknown>[] : Array.isArray(data.marks) ? (data.marks as Record<string, unknown>[]).filter((mark)=>mark.kind==="mark") : [];
        const items: WorkItem[] = rawItems.map((item,index)=>({ id:String(item.id??item.annotationId??`${id}-${index}`), drawingId:id, label:String(item.label??item.name??`Work item ${index+1}`), status:typeof item.status==="string"?item.status:undefined, updatedAt:String(item.updatedAt??item.createdAt??"") }));
        const completed=items.filter((item)=>item.status==="Complete").length;
        const inProgress=items.filter((item)=>item.status==="In Progress").length;
        const area=String(data.area??"").trim(); const revision=String(data.revision??"").trim();
        const relatedRecords=Array.isArray(data.relatedRecords)?data.relatedRecords.map(String):[];
        return { id,title:String(data.name??data.fileName??"Drawing").replace(/\.[^.]+$/, ""),subtitle:[revision?`Rev ${revision}`:"Drawing",area].filter(Boolean).join(" · "),revision,date:String(data.updatedAt??data.createdAt??""),createdAt:String(data.createdAt??""),updatedAt:String(data.updatedAt??""),image:typeof data.downloadURL==="string"?data.downloadURL:undefined,type:"drawing",workItems:items.length,complete:completed,inProgress,openItems:Math.max(0,items.length-completed-inProgress),items,filePath:String(data.storagePath??""),mimeType:String(data.mimeType??data.contentType??""),area,syncPending:data.storagePending===true,projectId:String(data.projectId??""),relatedCount:relatedRecords.length,relatedRecords };
      });
      const nextDocuments: WorkspaceRecord[] = documentSnapshot.docs.map((snapshot) => {
        const data=snapshot.data(); const type=data.type as RecordType;
        const date=String(data.documentDate||data.recordDate||data.createdAt||"");
        const title=String(data.title??data.fileName??(type==="PHOTO"?"Site photo":type==="TBT"?"Toolbox talk":"Daily Progress Report"));
        const status=type==="DPR"?(data.ocrStatus==="processed"?"Text extracted":data.ocrStatus==="needs-ocr"?"Review source document":"Daily progress report"):type==="TBT"?[String(data.topic??"Toolbox talk"),"Shift record"].join(" · "):type==="PHOTO"?"Site photo":"Project document";
        const extracted=data.extracted&&typeof data.extracted==="object"?data.extracted as Record<string,unknown>:{};
        const confirmed=Array.isArray(data.confirmedFields)?data.confirmedFields as string[]:[];
        const suggestions=Array.isArray(data.drawingSuggestions)?data.drawingSuggestions as {drawingName?:string;confirmed?:boolean}[]:[];
        const relatedRecords=Array.isArray(data.relatedRecords)?data.relatedRecords.map(String):[];
        return { id:snapshot.id,title,subtitle:status,date,createdAt:String(data.createdAt??""),uploadedAt:String(data.createdAt??""),updatedAt:String(data.updatedAt??data.createdAt??""),type,workItems:0,complete:0,inProgress:0,openItems:0,filePath:String(data.filePath??""),mimeType:String(data.mimeType??""),fileName:String(data.fileName??title),image:typeof data.downloadURL==="string"?data.downloadURL:undefined,area:String(data.area??extracted.area??""),topic:String(data.topic??""),manpower:type==="TBT"?String(data.manpower??""):confirmed.includes("manpower")?String(extracted.manpower??""):"",workers:String(data.workers??""),staff:String(data.staff??""),projectId:String(data.projectId??""),drawingLinks:suggestions.filter((item)=>item.confirmed&&item.drawingName).map((item)=>String(item.drawingName)),relatedCount:relatedRecords.length,relatedRecords };
      }).filter((record)=>["DPR","TBT","PHOTO","DOCUMENT"].includes(record.type));
      const todayKey=localDay();
      const dayEvents=drawingRows.flatMap(({id,data})=>(Array.isArray(data.workEvents)?data.workEvents as DailyEvent[]:[]).filter((event)=>event.localDate===todayKey).map((event)=>({...event,drawingId:event.drawingId||id})));
      setDrawings(nextDrawings); setDocuments(nextDocuments); setEvents(dayEvents); setLoadFailed(false);
    } catch (error) {
      console.error("Workspace records could not be loaded",error);
      setLoadFailed(true);
      setMessage("Could not check your latest saved records. Check the connection and retry.");
    } finally { setBusy(false); }
  },[user]);

  useEffect(()=>{let cancelled=false;void Promise.resolve().then(()=>{if(!cancelled) return load();});return()=>{cancelled=true;};},[load]);
  useEffect(()=>{const update=()=>setOnline(navigator.onLine);update();window.addEventListener("online",update);window.addEventListener("offline",update);return()=>{window.removeEventListener("online",update);window.removeEventListener("offline",update);};},[]);

  const todayKey=localDay();
  const allRecords=useMemo(()=>[...drawings,...documents].sort((a,b)=>String(b.updatedAt??b.date).localeCompare(String(a.updatedAt??a.date))),[drawings,documents]);
  const visibleRecords=useMemo(()=>allRecords.filter((record)=>(filter==="all"||record.type===filter)&&(!query.trim()||`${record.title} ${record.subtitle} ${record.date} ${record.type} ${record.area??""} ${record.revision??""}`.toLowerCase().includes(query.trim().toLowerCase()))),[allRecords,filter,query]);
  const groups=useMemo(()=>{const months=new Map<string,Map<string,WorkspaceRecord[]>>();for(const record of visibleRecords){const date=recordDay(record.date);const month=date==="undated"?"undated":date.slice(0,7);if(!months.has(month))months.set(month,new Map());const days=months.get(month)!;if(!days.has(date))days.set(date,[]);days.get(date)!.push(record);}return [...months.entries()].sort(([a],[b])=>b.localeCompare(a));},[visibleRecords]);
  const latestByWork=new Map<string,DailyEvent>();
  for(const event of events){const key=`${event.drawingId}:${event.workItemId}`;const previous=latestByWork.get(key);if(!previous||String(event.timestamp)>String(previous.timestamp))latestByWork.set(key,event);}
  const activeUpdates=[...latestByWork.values()].filter((event)=>event.action!=="deleted");
  const everyWorkItem=drawings.flatMap((drawing)=>drawing.items??[]);
  const completed=everyWorkItem.filter((item)=>item.status==="Complete").length;
  const inProgress=everyWorkItem.filter((item)=>item.status==="In Progress").length;
  const openItems=Math.max(0,everyWorkItem.length-completed-inProgress);
  const updatedToday=new Set(activeUpdates.map((event)=>`${event.drawingId}:${event.workItemId}`)).size;
  const activeDrawings=drawings.slice(0,3);
  const activeDrawing=activeDrawings[0];
  const todayDocuments=documents.filter((record)=>recordDay(record.uploadedAt||record.createdAt||record.date)===todayKey);
  const todayDpr=todayDocuments.filter((record)=>record.type==="DPR");
  const todayTbt=todayDocuments.filter((record)=>record.type==="TBT");
  const todayPhotos=todayDocuments.filter((record)=>record.type==="PHOTO");
  const todayDocs=todayDocuments.filter((record)=>record.type==="DOCUMENT");
  const todayDrawings=drawings.filter((record)=>recordDay(record.updatedAt||record.date)===todayKey);
  const manpowerRecord=[...todayTbt,...todayDpr].find((record)=>Number(record.manpower)>0);
  const manpower=manpowerRecord?Number(manpowerRecord.manpower):0;
  const workers=[...todayTbt,...todayDpr].map((record)=>Number(record.workers)).find((value)=>Number.isFinite(value)&&value>0)??0;
  const staff=[...todayTbt,...todayDpr].map((record)=>Number(record.staff)).find((value)=>Number.isFinite(value)&&value>0)??0;
  const pendingDrawing=drawings.find((record)=>record.syncPending);
  const todayRecords=allRecords.filter((record)=>recordDay(record.uploadedAt||record.date)===todayKey);

  const activity=useMemo(()=>{
    const items:ActivityItem[]=[];
    const eventsByDrawing=new Map<string,DailyEvent[]>();
    for(const event of activeUpdates){const group=eventsByDrawing.get(event.drawingId)??[];group.push(event);eventsByDrawing.set(event.drawingId,group);}
    for(const drawing of drawings){
      const drawingEvents=eventsByDrawing.get(drawing.id)??[];
      if(drawingEvents.length){items.push({id:`drawing-${drawing.id}`,type:"drawing",title:`${drawing.title}${drawing.revision?` · Rev ${drawing.revision}`:""}`,details:`${drawingEvents.length} work item${drawingEvents.length===1?"":"s"} updated${drawing.area?` · ${drawing.area}`:""}`,time:drawingEvents.map((event)=>event.timestamp??"").sort().at(-1)??drawing.updatedAt??"",drawingId:drawing.id});}
      else if(recordDay(drawing.createdAt??"")===todayKey){items.push({id:`drawing-${drawing.id}`,type:"drawing",title:`${drawing.title}${drawing.revision?` · Rev ${drawing.revision}`:""}`,details:`Drawing added${drawing.area?` · ${drawing.area}`:""}`,time:drawing.createdAt??"",drawingId:drawing.id});}
    }
    const dayDocs=todayDocuments.filter((record)=>record.type!=="PHOTO");
    for(const record of dayDocs){items.push({id:`${record.type}-${record.id}`,type:record.type,title:record.type==="DPR"?"Daily progress report":record.type==="TBT"?(record.topic||record.title):record.title,details:record.type==="TBT"?[record.area,record.workers?`${record.workers} workers`:""].filter(Boolean).join(" · ")||"Toolbox talk added":record.type==="DPR"?"DPR added to today’s work":record.subtitle,time:record.createdAt||record.updatedAt||record.date,recordId:record.id});}
    if(todayPhotos.length){const newest=[...todayPhotos].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0];items.push({id:"photos-today",type:"PHOTO",title:"Site photos",details:`${todayPhotos.length} photo${todayPhotos.length===1?"":"s"}${todayPhotos[0]?.area?` · ${todayPhotos[0].area}`:""}`,time:newest?.createdAt||newest?.date||"",recordId:newest?.id,photoCount:todayPhotos.length});}
    return items.sort((a,b)=>String(a.time).localeCompare(String(b.time)));
  },[activeUpdates,drawings,todayDocuments,todayKey,todayPhotos]);

  const syncStatus=uploading?{kind:"saving",label:"Saving…"}:!online?{kind:"offline",label:"Offline · sync status unavailable"}:loadFailed?{kind:"failed",label:"Sync check failed · Retry"}:pendingDrawing?{kind:"pending",label:"Drawing sync pending"}:busy?{kind:"checking",label:"Checking saved records…"}:{kind:"saved",label:"All changes saved"};
  const count=(type:RecordType)=>allRecords.filter((record)=>record.type===type).length;
  const typeOptions:["all"|RecordType,string,number][]=[["all","All",allRecords.length],["drawing","Drawings",count("drawing")],["DPR","DPR",count("DPR")],["TBT","TBT",count("TBT")],["PHOTO","Photos",count("PHOTO")],["DOCUMENT","Documents",count("DOCUMENT")]];
  const icon=(type:RecordType)=>type==="drawing"?<BookOpen size={17}/>:type==="PHOTO"?<ImageIcon size={17}/>:type==="TBT"?<ShieldCheck size={17}/>:<FileText size={17}/>;

  function downloadCsv(){const rows=[["Date","Record type","Name","Area","Status","Work items","Complete","Manpower"],...visibleRecords.map((record)=>[dateText(recordDay(record.date)),labels[record.type],record.title,record.area||"",record.subtitle,String(record.workItems),String(record.complete),record.manpower||""])];const csv=rows.map((row)=>row.map((value)=>`"${String(value).replace(/"/g,'""')}"`).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob(["\ufeff",csv],{type:"text/csv;charset=utf-8"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=`epcx-field-records-${localDay()}.csv`;anchor.click();URL.revokeObjectURL(url);}
  async function downloadExcel(){const ExcelJS=await import("exceljs");const workbook=new ExcelJS.default.Workbook();const sheet=workbook.addWorksheet("Field Records");sheet.columns=[{header:"Date",key:"date",width:16},{header:"Record type",key:"type",width:14},{header:"Name",key:"name",width:34},{header:"Area",key:"area",width:22},{header:"Status",key:"status",width:22},{header:"Work items",key:"items",width:13},{header:"Complete",key:"complete",width:12},{header:"Manpower",key:"manpower",width:12}];for(const record of visibleRecords)sheet.addRow({date:dateText(recordDay(record.date)),type:labels[record.type],name:record.title,area:record.area||"",status:record.subtitle,items:record.workItems,complete:record.complete,manpower:record.manpower||""});sheet.getRow(1).font={bold:true};const buffer=await workbook.xlsx.writeBuffer();const url=URL.createObjectURL(new Blob([buffer],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=`epcx-field-records-${localDay()}.xlsx`;anchor.click();URL.revokeObjectURL(url);}
  function printReport(title:string,records:WorkspaceRecord[]){const popup=window.open("","_blank");if(!popup){setMessage("Allow pop-ups to print or save this report as a PDF.");return;}const escape=(value:string)=>value.replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));const rows=records.map((record)=>`<tr><td>${escape(dateText(recordDay(record.date)))}</td><td>${escape(labels[record.type])}</td><td>${escape(record.title)}</td><td>${escape(record.area||"—")}</td><td>${escape(record.subtitle)}</td></tr>`).join("");popup.document.write(`<!doctype html><html><head><title>${escape(title)}</title><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:14px Arial,sans-serif;color:#1d3025;padding:32px}h1{font-size:24px;margin-bottom:4px}p{color:#596a5f}table{width:100%;border-collapse:collapse;margin-top:22px}th,td{text-align:left;border-bottom:1px solid #dbe3dc;padding:10px 8px}th{background:#eef4ef;color:#365642}@media print{body{padding:0}}</style></head><body><h1>${escape(title)}</h1><p>${escape(project?.name||"EPCX Field Records")} · ${escape(dateText(localDay()))} · ${records.length} records</p><table><thead><tr><th>Date</th><th>Type</th><th>Record</th><th>Area</th><th>Details</th></tr></thead><tbody>${rows||"<tr><td colspan='5'>No records for this date.</td></tr>"}</tbody></table></body></html>`);popup.document.close();popup.focus();window.setTimeout(()=>popup.print(),300);}

  function startUpload(type:"TBT"|"PHOTO"|"DOCUMENT"){setMenuOpen(false);if(!accountUser){setMessage("Sign in to save field records to your workspace.");return;}if(type==="TBT"){setTbtDetails((old)=>({...old,date:localDay()}));setTbtDialogOpen(true);return;}(type==="PHOTO"?photoInputRef:documentInputRef).current?.click();}
  function chooseTbtFile(){setTbtDialogOpen(false);window.setTimeout(()=>tbtInputRef.current?.click(),0);}
  async function uploadFiles(type:"TBT"|"PHOTO"|"DOCUMENT",files:FileList|null){if(!files||!user||user.isAnonymous)return;const selected=Array.from(files);const added:WorkspaceRecord[]=[];setUploading(true);setMessage("");try{for(const file of selected){const id=crypto.randomUUID();const timestamp=new Date().toISOString();const date=type==="TBT"?tbtDetails.date||localDay():localDay();const path=`documents/${user.uid}/field-records/${id}/original`;const downloadURL=await uploadDocument(file,user.uid,null,()=>{},{folder:`field-records/${id}`,objectName:"original"});const title=type==="TBT"&&tbtDetails.topic.trim()?tbtDetails.topic.trim():file.name.replace(/\.[^.]+$/,"")||labels[type];const record={id,ownerUid:user.uid,createdBy:user.uid,updatedBy:user.uid,type,title,fileName:file.name,filePath:path,downloadURL,mimeType:file.type||"application/octet-stream",attachments:[{filePath:path,fileName:file.name,mimeType:file.type||"application/octet-stream"}],recordDate:date,documentDate:date,createdAt:timestamp,updatedAt:timestamp,projectId:project?.id||null,projectName:project?.name||"",area:type==="TBT"?tbtDetails.area:"",topic:type==="TBT"?tbtDetails.topic:"",supervisor:type==="TBT"?tbtDetails.supervisor:"",manpower:type==="TBT"?tbtDetails.manpower:"",workers:type==="TBT"?tbtDetails.workers:"",staff:type==="TBT"?tbtDetails.staff:"",remarks:type==="TBT"?tbtDetails.remarks:"",discipline:"",tags:[],status:"active",relatedRecords:[],ocrStatus:type==="TBT"?"needs-ocr":"not-applicable",rawOcrText:"",extracted:{},confirmedFields:[]};try{await setDoc(doc(db,"users",user.uid,"fieldDocuments",id),record);}catch(error){await deleteDocument(path).catch(()=>undefined);throw error;}added.push({id,title,subtitle:type==="TBT"?[record.topic||"Toolbox talk","Shift record"].join(" · "):type==="DOCUMENT"?"Project document":"Site photo",date,createdAt:timestamp,uploadedAt:timestamp,updatedAt:timestamp,type,workItems:0,complete:0,inProgress:0,openItems:0,filePath:path,mimeType:record.mimeType,fileName:file.name,image:(type==="PHOTO"||type==="DOCUMENT")&&record.mimeType.startsWith("image/")?downloadURL:undefined,area:record.area,topic:record.topic,manpower:record.manpower,workers:record.workers,staff:record.staff});}setDocuments((old)=>[...added,...old]);setMessage(`${added.length} ${type==="PHOTO"?added.length===1?"photo":"photos":type==="TBT"?"TBT record":"document"} added to today’s work.`);}catch(error){console.error("Field record upload failed",error);if(added.length)setDocuments((old)=>[...added,...old]);setMessage(added.length?`${added.length} record${added.length===1?"":"s"} saved. The next upload failed; check your connection and retry.`:"Upload could not be completed. Check your connection and Storage access, then retry.");}finally{setUploading(false);if(tbtInputRef.current)tbtInputRef.current.value="";if(photoInputRef.current)photoInputRef.current.value="";if(documentInputRef.current)documentInputRef.current.value="";}}

  function openRecord(record:WorkspaceRecord){if(record.type==="drawing")onOpenDrawing(record.id);else if(record.type==="DPR")onOpenDpr(record.id);else onOpenRecord?.(record.id);}
  const continueWork=()=>activeDrawing?onOpenDrawing(activeDrawing.id):onContinueWork?.();
  const siteArea=activeDrawing?.area||project?.areas.split(",").map((area)=>area.trim()).find(Boolean)||"Site area not set";

  return <main className={`field-dashboard field-workspace-home${reports?" is-reports":""}`}>
    <input ref={tbtInputRef} hidden type="file" accept={accepted} onChange={(event)=>void uploadFiles("TBT",event.target.files)}/>
    <input ref={photoInputRef} hidden type="file" accept=".jpg,.jpeg,.png,.webp" multiple onChange={(event)=>void uploadFiles("PHOTO",event.target.files)}/>
    <input ref={documentInputRef} hidden type="file" accept={accepted} onChange={(event)=>void uploadFiles("DOCUMENT",event.target.files)}/>

    {tbtDialogOpen&&<div className="field-modal-backdrop" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)setTbtDialogOpen(false);}}><section className="field-tbt-dialog" role="dialog" aria-modal="true" aria-labelledby="field-tbt-title"><header><span><ShieldCheck size={18}/>TOOLBOX TALK</span><h2 id="field-tbt-title">Add today&apos;s TBT</h2><p>Record the details you know, then attach the original sheet or photo.</p></header><div className="field-tbt-fields"><label>Date<input type="date" value={tbtDetails.date} onChange={(event)=>setTbtDetails((old)=>({...old,date:event.target.value}))}/></label><label>Area<input value={tbtDetails.area} onChange={(event)=>setTbtDetails((old)=>({...old,area:event.target.value}))} placeholder="e.g. Pipe rack north"/></label><label className="wide">Topic<input value={tbtDetails.topic} onChange={(event)=>setTbtDetails((old)=>({...old,topic:event.target.value}))} placeholder="Toolbox talk topic"/></label><label>Supervisor<input value={tbtDetails.supervisor} onChange={(event)=>setTbtDetails((old)=>({...old,supervisor:event.target.value}))}/></label><label>Manpower<input type="number" min="0" value={tbtDetails.manpower} onChange={(event)=>setTbtDetails((old)=>({...old,manpower:event.target.value}))}/></label><label>Workers<input type="number" min="0" value={tbtDetails.workers} onChange={(event)=>setTbtDetails((old)=>({...old,workers:event.target.value}))}/></label><label>Staff / supervisors<input type="number" min="0" value={tbtDetails.staff} onChange={(event)=>setTbtDetails((old)=>({...old,staff:event.target.value}))}/></label><label className="wide">Remarks<input value={tbtDetails.remarks} onChange={(event)=>setTbtDetails((old)=>({...old,remarks:event.target.value}))} placeholder="Optional note"/></label></div><footer><button className="secondary" onClick={()=>setTbtDialogOpen(false)}>Cancel</button><button onClick={chooseTbtFile}><ShieldCheck size={16}/>Attach sheet or photo</button></footer></section></div>}

    {reports ? <>
      <header className="field-dashboard-heading"><div><p className="field-dashboard-kicker">{project?.name||"EPCX FIELD RECORDS"}</p><h1>Reports &amp; exports</h1><p>Print a clear daily record or export structured field data.</p></div></header>
    </> : <>
      <header className="field-workspace-intro">
        <div className="field-workspace-intro-copy"><p className="field-dashboard-kicker">SITE DESK <span/> TODAY</p><h1>Today&apos;s field work</h1><p className="field-workspace-project-line"><CalendarDays size={15}/>{dateText(todayKey)}<i/>{project?.name||"Set up your project"}</p><p className="field-workspace-subline">Keep today&apos;s work, documents and site evidence together.</p><div className="field-workspace-site-context"><span><Building2 size={14}/>PROJECT <b>{project?.name||"Project not set"}</b></span><span><MapPin size={14}/>SITE / AREA <b>{siteArea}</b></span>{project?.projectNumber&&<span>PROJECT NO. <b>{project.projectNumber}</b></span>}</div></div>
        <div className="field-workspace-actions"><div className={`field-sync-state ${syncStatus.kind}`} role="status">{syncStatus.kind==="saving"||syncStatus.kind==="checking"?<LoaderCircle size={14} className="spin"/>:syncStatus.kind==="failed"?<AlertTriangle size={14}/>:syncStatus.kind==="saved"?<CheckCircle2 size={14}/>:<Cloud size={14}/>}<span>{syncStatus.label}</span>{loadFailed&&<button onClick={()=>void load()} aria-label="Retry checking saved records"><RefreshCw size={13}/></button>}{pendingDrawing&&<button onClick={()=>onOpenDrawing(pendingDrawing.id)}>Retry drawing sync</button>}</div><button className="field-continue-button" onClick={continueWork}><ArrowRight size={16}/><span>Continue today&apos;s work</span></button><div className="field-workspace-add-wrap"><button className="field-add-button" onClick={()=>setMenuOpen((open)=>!open)} aria-expanded={menuOpen} disabled={uploading}><Plus size={18}/><span>{uploading?"Saving…":"Add record"}</span></button>{menuOpen&&<div className="field-add-menu-backdrop" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)setMenuOpen(false);}}><div className="field-add-menu" role="menu"><div><b>Add to today&apos;s work</b><button className="field-add-menu-close" onClick={()=>setMenuOpen(false)} aria-label="Close"><X size={17}/></button></div><button role="menuitem" onClick={()=>{setMenuOpen(false);onAddDrawing();}}><BookOpen size={18}/><span><b>Drawing</b><small>Mark work on an engineering drawing</small></span></button><button role="menuitem" onClick={()=>{setMenuOpen(false);onAddDpr();}}><FileText size={18}/><span><b>DPR</b><small>Upload today&apos;s report</small></span></button><button role="menuitem" onClick={()=>startUpload("TBT")}><ShieldCheck size={18}/><span><b>TBT</b><small>Add a toolbox talk</small></span></button><button role="menuitem" onClick={()=>startUpload("PHOTO")}><ImageIcon size={18}/><span><b>Photo</b><small>Add site photos</small></span></button><button role="menuitem" onClick={()=>startUpload("DOCUMENT")}><FileText size={18}/><span><b>Document</b><small>Add a supporting record</small></span></button></div></div>}</div></div>
      </header>

      {message&&<div className={`field-record-message ${loadFailed?"error":""}`} role="status">{message}<button onClick={()=>setMessage("")} aria-label="Dismiss"><X size={15}/></button></div>}
      {!accountUser&&!loading&&<div className="field-record-empty">Sign in once to keep your field records with your account. <a href="/login?redirect=%2Fstart">Sign in</a></div>}
      {busy&&<div className="field-record-empty"><LoaderCircle size={17} className="spin"/> Checking today&apos;s saved work…</div>}

      {accountUser&&!busy&&!loadFailed&&<>
        <section className="field-work-progress" aria-label="Today's work progress">
          <div className="field-work-progress-main"><div className="field-work-progress-head"><div><p className="field-section-kicker">TODAY&apos;S FIELD STATUS</p><h2>Work progress</h2></div><span>{updatedToday} work item{updatedToday===1?"":"s"} updated today</span></div><div className="field-work-progress-bar"><i style={{width:`${everyWorkItem.length?Math.round(completed/everyWorkItem.length*100):0}%`}}/></div><div className="field-work-progress-counts"><span><b>{completed}</b><small>Complete</small></span><span><b>{inProgress}</b><small>In progress</small></span><span><b>{openItems}</b><small>Needs status</small></span><span className="field-work-progress-total"><b>{everyWorkItem.length}</b><small>Work items</small></span></div></div>
          <div className="field-work-support-status"><div><span><Users size={15}/>MANPOWER</span><b>{manpower?`${manpower} recorded`:workers||staff?`${workers||0} workers · ${staff||0} supervisors`:"Not recorded"}</b>{(workers||staff)&&<small>{workers} workers · {staff} supervisors</small>}</div><div><span><ClipboardList size={15}/>TODAY&apos;S RECORDS</span><b>{todayDpr.length?"DPR added":"DPR not added"} <i/> {todayTbt.length?"TBT added":"TBT not added"}</b><small>{todayPhotos.length} photos · {todayDocs.length} supporting records</small></div><div><span><BookOpen size={15}/>DRAWINGS</span><b>{drawings.length} active · {todayDrawings.length} updated today</b><small>{drawings.length?"Field work stays anchored to a drawing":"Add a drawing to start today’s work"}</small></div></div>
        </section>

        <section className="field-needs-attention"><header><div><p className="field-section-kicker">NEXT ACTIONS</p><h2>Needs attention</h2></div><span>{(!drawings.length?1:0)+(todayDpr.length?0:1)+(openItems+inProgress?1:0)+(todayTbt.length||manpower?0:1)} items</span></header><div className="field-attention-list">
          {!drawings.length&&<article><span className="attention-icon"><BookOpen size={17}/></span><div><b>No drawing in today&apos;s work</b><small>Add the drawing the team is working from.</small></div><button onClick={onAddDrawing}>Add drawing <ChevronRight size={15}/></button></article>}
          {!todayDpr.length&&<article><span className="attention-icon"><FileText size={17}/></span><div><b>Today&apos;s DPR not added</b><small>Keep the shift report with the work recorded today.</small></div><button onClick={onAddDpr}>Upload DPR <ChevronRight size={15}/></button></article>}
          {(inProgress+openItems)>0&&<article><span className="attention-icon"><CircleDashed size={17}/></span><div><b>{inProgress+openItems} work item{inProgress+openItems===1?"":"s"} still need a status</b><small>{activeDrawing?`${activeDrawing.title}${activeDrawing.revision?` · Rev ${activeDrawing.revision}`:""} · ${activeDrawing.area||"Drawing area"}`:"Open a drawing to review work status."}</small></div><button onClick={continueWork}>Review work <ChevronRight size={15}/></button></article>}
          {!todayTbt.length&&!manpower&&<article><span className="attention-icon"><ShieldCheck size={17}/></span><div><b>TBT and manpower not recorded</b><small>Add the toolbox talk details for this shift.</small></div><button onClick={()=>startUpload("TBT")}>Add TBT <ChevronRight size={15}/></button></article>}
          {pendingDrawing&&<article><span className="attention-icon"><Cloud size={17}/></span><div><b>Drawing sync is waiting</b><small>{pendingDrawing.title} is saved on this device and needs cloud sync.</small></div><button onClick={()=>onOpenDrawing(pendingDrawing.id)}>Retry sync <ChevronRight size={15}/></button></article>}
          {!drawings.length&&todayDpr.length&&todayTbt.length&&<div className="field-attention-clear"><CheckCircle2 size={17}/>No urgent follow-up from the records saved today.</div>}
        </div></section>

        <section className="field-active-drawings"><header><div><p className="field-section-kicker">WORK ANCHOR</p><h2>Active drawing</h2></div><button onClick={onAddDrawing}><Plus size={15}/>Add drawing</button></header>{activeDrawing?<div className="field-active-drawing-list">{activeDrawings.map((drawing)=>{const isImage=drawing.image&&drawing.mimeType?.startsWith("image/");return <article className="field-active-drawing" key={drawing.id}><button className="field-active-drawing-preview" onClick={()=>onOpenDrawing(drawing.id)} aria-label={`Open ${drawing.title}`}>{isImage?<img src={drawing.image} alt=""/>:<span className="field-drawing-file-mark"><BookOpen size={27}/><small>{drawing.mimeType?.includes("pdf")?"PDF":"DRAWING"}</small></span>}<span className="field-drawing-preview-status"><Check size={12}/>FIELD DRAWING</span></button><div className="field-active-drawing-info"><div className="field-active-drawing-title"><span><b>{drawing.title}{drawing.revision?` · Rev ${drawing.revision}`:""}</b><small>{drawing.area||project?.name||"Site area not set"}</small></span>{recordDay(drawing.updatedAt||"")===todayKey&&<i>Updated today</i>}</div><div className="field-active-drawing-stats"><span><b>{drawing.workItems}</b> work items</span><span><b>{drawing.complete}</b> complete</span><span><b>{drawing.inProgress+drawing.openItems}</b> still open</span></div><div className="field-active-drawing-progress"><i style={{width:`${drawing.workItems?Math.round(drawing.complete/drawing.workItems*100):0}%`}}/></div><button className="field-open-drawing" onClick={()=>onOpenDrawing(drawing.id)}>Open drawing <ArrowRight size={15}/></button></div></article>;})}</div>:<div className="field-empty-drawing"><BookOpen size={23}/><div><b>No drawing in this project yet</b><span>Add the drawing your team uses to anchor work items and daily records.</span></div><button onClick={onAddDrawing}>Add drawing <ArrowRight size={15}/></button></div>}</section>

        <section className="field-quick-capture"><header><div><p className="field-section-kicker">QUICK CAPTURE</p><h2>Add to today&apos;s work</h2></div><span>Choose what you have on site.</span></header><div className="field-quick-actions"><button onClick={onAddDrawing}><span><BookOpen size={20}/></span><b>Drawing</b><small>Mark work</small></button><button onClick={onAddDpr}><span><FileText size={20}/></span><b>DPR</b><small>Upload today&apos;s report</small></button><button onClick={()=>startUpload("TBT")}><span><ShieldCheck size={20}/></span><b>TBT</b><small>Add toolbox talk</small></button><button onClick={()=>startUpload("PHOTO")}><span><ImageIcon size={20}/></span><b>Photo</b><small>Add site photos</small></button><button onClick={()=>startUpload("DOCUMENT")}><span><FileSpreadsheet size={20}/></span><b>Document</b><small>Supporting record</small></button></div></section>

        <section className="field-today-activity"><header><div><p className="field-section-kicker">{dateText(todayKey).toUpperCase()} · PROJECT ACTIVITY</p><h2>Today&apos;s work</h2><p>Drawings, progress and supporting records from the shift.</p></div><button onClick={onOpenProject}><MapPin size={14}/>{siteArea}</button></header><div className="field-today-record-chain"><span><BookOpen size={14}/>Drawing</span><i/><span><Check size={14}/>Work items</span><i/><span><FileText size={14}/>DPR {todayDpr.length?"✓":"—"}</span><i/><span><ShieldCheck size={14}/>TBT {todayTbt.length?"✓":"—"}</span><i/><span><ImageIcon size={14}/>Photos {todayPhotos.length}</span></div>{activity.length?<div className="field-activity-timeline">{activity.map((item)=><article key={item.id}><time>{timeText(item.time)}</time><span className={`field-activity-icon ${item.type.toLowerCase()}`}>{icon(item.type)}</span><div><b>{item.title}</b><small>{item.details}</small></div><button onClick={()=>item.drawingId?onOpenDrawing(item.drawingId):item.recordId?openRecord(allRecords.find((record)=>record.id===item.recordId)??{id:item.recordId,type:item.type,title:item.title,subtitle:item.details,date:todayKey,workItems:0,complete:0,inProgress:0,openItems:0}):undefined}>{item.type==="drawing"?"Open drawing":item.type==="PHOTO"?"View photos":item.type==="DPR"?"Open DPR":"Open record"}<ArrowRight size={14}/></button></article>)}</div>:<div className="field-activity-empty"><Clock3 size={18}/><span><b>No activity recorded today yet.</b><small>Start with the drawing, DPR, TBT or photos you already have.</small></span></div>}</section>
      </>}


      {accountUser&&!busy&&<section className="field-recent-section"><header className="field-recent-heading"><div><p className="field-section-kicker">FIND THE DAY AGAIN</p><h2>Recent records</h2><p>Grouped by date, project and work — no folders to create.</p></div><label className="field-record-search"><Search size={16}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search drawings, work items, dates or records"/><kbd>⌘ K</kbd></label></header><div className="field-record-filter" role="tablist" aria-label="Filter recent records">{typeOptions.map(([value,label,total])=><button key={value} role="tab" aria-selected={filter===value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{label}<span>{total}</span></button>)}</div>{!visibleRecords.length?<div className="field-record-empty">{query?"No records match that search.":filter==="all"?"No records have been added yet.":`No ${labels[filter as RecordType].toLowerCase()} records yet.`}</div>:<div className="field-month-groups">{groups.map(([month,days],monthIndex)=><details key={month} open={monthIndex===0} className="field-month-group"><summary><CalendarDays size={16}/><b>{monthText(month)}</b><span>{[...days.values()].flat().length} records</span></summary>{[...days.entries()].sort(([a],[b])=>b.localeCompare(a)).map(([day,records])=><section className="field-date-group" key={day}><h3>{dateText(day)}{records.filter((record)=>record.type==="PHOTO").length>0&&<span className="field-date-photo-count"> · {records.filter((record)=>record.type==="PHOTO").length} photos</span>}</h3><div className="field-record-list">{records.map((record)=><button className="field-record-row" key={`${record.type}-${record.id}`} onClick={()=>openRecord(record)}><span className={`field-record-thumb ${record.type.toLowerCase()}`}>{record.image&&record.mimeType?.startsWith("image/")?<img src={record.image} alt=""/>:icon(record.type)}</span><span className="field-record-main"><b>{record.title}</b><small>{labels[record.type]} · {record.subtitle}</small>{record.type==="drawing"&&<small>{record.workItems} work items · {record.complete} complete{record.area?` · ${record.area}`:""}</small>}{record.relatedCount?<small>Related records · {record.relatedCount} linked</small>:null}{record.type==="DPR"&&record.drawingLinks?.length?<small>Related drawings · {record.drawingLinks.join(", ")}</small>:null}</span><span className="field-record-updated">{record.type==="drawing"?"Open drawing":"Open record"}</span></button>)}</div></section>)}</details>)}</div>}</section>}
    </>}

  </main>;
}
