"use client";

import { useCallback, useEffect, useMemo, useState, type ChangeEvent } from "react";
import { AlertTriangle, ArrowDownToLine, CirclePlus, FileSpreadsheet, Plus, RefreshCw, Search, Settings2, Wrench } from "lucide-react";
import { useBillCheckWorkspace } from "@/components/billcheck/use-billcheck-workspace";
import { PdfDrawingViewer } from "./PdfDrawingViewer";
import { addJoint, createFieldProject, drawingObjectUrl, importJoints, listFieldProjects, listJointEvents, listJoints, listProjectEvents, recordJointEvent, updateFieldProgressEditors, updateJointPin, updateProjectSettings, type FieldProject } from "@/lib/field-progress/data";
import { computeFieldProgress, DEFAULT_FIELD_STAGES, newerDrawingRevisions, normalizeDrawingPoint, type JointEvent, type JointRecord } from "@/lib/field-progress/core";

type EventWithJoint = JointEvent & { jointId: string };
const isoNow = () => new Date().toISOString().slice(0,16);
const asText = (value: unknown) => typeof value === "string" ? value : "";

export function FieldProgressWorkspace() {
  const workspace = useBillCheckWorkspace();
  const [projects,setProjects]=useState<FieldProject[]>([]); const [project,setProject]=useState<FieldProject|null>(null); const [joints,setJoints]=useState<JointRecord[]>([]); const [events,setEvents]=useState<EventWithJoint[]>([]);
  const [pdfUrl,setPdfUrl]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [queryText,setQueryText]=useState(""); const [selected,setSelected]=useState<JointRecord|null>(null);
  const [creating,setCreating]=useState(false); const [projectForm,setProjectForm]=useState({name:"",lineNumber:"",drawingNumber:"",revision:"",areaSystem:"",workPackage:""}); const [drawingFile,setDrawingFile]=useState<File|null>(null);
  const [showJointForm,setShowJointForm]=useState(false); const [jointForm,setJointForm]=useState({id:"",drawingPage:"1",jointType:"",weldType:"Field weld",size:"",material:"",spool:"",remarks:""});
  const [eventForm,setEventForm]=useState({stage:"Planned",occurredAt:isoNow(),crew:"",welder:"",wps:"",remarks:"",inspectionReference:"",inspectionResult:"",reason:"",correctionOf:""}); const [confirmed,setConfirmed]=useState(false); const [saving,setSaving]=useState(false); const [configOpen,setConfigOpen]=useState(false); const [stagesDraft,setStagesDraft]=useState(""); const [pinMode,setPinMode]=useState(false);
  const [editorsDraft,setEditorsDraft]=useState<string[]>([]); const [accessOpen,setAccessOpen]=useState(false); const [transitionsDraft,setTransitionsDraft]=useState(""); const [prerequisitesDraft,setPrerequisitesDraft]=useState("");
  const [windowStart,setWindowStart]=useState(""); const [windowEnd,setWindowEnd]=useState("");
  const isEditor=Boolean(workspace.user&&workspace.organization&&(workspace.organization.adminIds?.includes(workspace.user.uid)||workspace.organization.fieldProgressEditorIds?.includes(workspace.user.uid)));
  const reload=useCallback(async()=>{if(!workspace.organization)return;setLoading(true);setError("");try{setProjects(await listFieldProjects(workspace.organization.id));}catch(e){setError(e instanceof Error?e.message:"Unable to load Field Progress projects.");}finally{setLoading(false);}},[workspace.organization]);
  useEffect(()=>{const timer=setTimeout(()=>void reload(),0);return()=>clearTimeout(timer);},[reload]);
  useEffect(()=>()=>{if(pdfUrl)URL.revokeObjectURL(pdfUrl);},[pdfUrl]);
  const loadProject=useCallback(async(item:FieldProject)=>{if(!workspace.organization)return;setProject(item);setSelected(null);setLoading(true);setError("");try{const [jointRows,allEvents,url]=await Promise.all([listJoints(workspace.organization.id,item.id),listProjectEvents(workspace.organization.id,item.id),item.drawingPath?drawingObjectUrl(item.drawingPath):Promise.resolve("")]);setJoints(jointRows);setEvents(allEvents);setPdfUrl(url);setEventForm((previous)=>({...previous,stage:item.stages?.[0]??DEFAULT_FIELD_STAGES[0]}));}catch(e){setError(e instanceof Error?e.message:"Unable to load the drawing and joint register. Please try again.");}finally{setLoading(false);}},[workspace.organization]);
  const progress=useMemo(()=>computeFieldProgress(joints,events,windowStart?new Date(`${windowStart}T00:00:00`):undefined,windowEnd?new Date(`${windowEnd}T23:59:59`):undefined),[joints,events,windowStart,windowEnd]);
  const newerRevisions=project?newerDrawingRevisions(project.revision,projects.filter((other)=>other.drawingNumber.toLowerCase()===project.drawingNumber.toLowerCase()).map((other)=>other.revision)):[];
  const filtered=joints.filter((joint)=>`${joint.jointId??joint.id} ${Object.values(joint.attributes??{}).join(" ")}`.toLowerCase().includes(queryText.toLowerCase()));
  async function createProject(event:ChangeEvent<HTMLFormElement>){event.preventDefault();if(!workspace.organization||!workspace.user||!drawingFile)return;setSaving(true);setError("");try{const created=await createFieldProject({organizationId:workspace.organization.id,...projectForm,drawing:drawingFile,createdBy:workspace.user.uid});await reload();await loadProject(created);setCreating(false);setNotice("Field Progress work package created.");}catch(e){setError(e instanceof Error?e.message:"Project could not be created.");}finally{setSaving(false);}}
  async function createJoint(event:ChangeEvent<HTMLFormElement>){event.preventDefault();if(!workspace.organization||!project)return;setSaving(true);try{await addJoint(workspace.organization.id,project.id,{id:jointForm.id,drawingPage:Number(jointForm.drawingPage)||undefined,attributes:{jointType:jointForm.jointType,weldType:jointForm.weldType,size:jointForm.size,material:jointForm.material,spool:jointForm.spool,remarks:jointForm.remarks}});await loadProject(project);setJointForm({id:"",drawingPage:"1",jointType:"",weldType:"Field weld",size:"",material:"",spool:"",remarks:""});setShowJointForm(false);setNotice("Joint added to the register. Record events separately when work occurs.");}catch(e){setError(e instanceof Error?e.message:"Joint could not be added.");}finally{setSaving(false);}}
  async function handleImport(file:File|undefined){if(!workspace.organization||!project||!file)return;setError("");try{const count=await importJoints(workspace.organization.id,project.id,file);await loadProject(project);setNotice(`${count} joints imported. No progress events were created.`);}catch(e){setError(e instanceof Error?e.message:"Joint list import failed.");}}
  async function savePin(x:number,y:number,page:number){if(!pinMode||!selected||!workspace.organization||!project)return;try{const point=normalizeDrawingPoint(x,y,0,0,1,1);await updateJointPin(workspace.organization.id,project.id,{id:selected.jointId??selected.id,x:point.x,y:point.y,drawingPage:page});await loadProject(project);setPinMode(false);setNotice(`Pin saved for ${selected.jointId??selected.id} on drawing page ${page}.`);}catch(e){setError(e instanceof Error?e.message:"Pin could not be saved.");}}
  async function saveEvent(event:ChangeEvent<HTMLFormElement>){event.preventDefault();if(!workspace.organization||!project||!selected||!workspace.user)return;setSaving(true);setError("");try{await recordJointEvent({organizationId:workspace.organization.id,projectId:project.id,jointId:selected.jointId??selected.id,...eventForm,occurredAt:new Date(eventForm.occurredAt).toISOString(),inspectionResult:eventForm.inspectionResult||undefined,correctionOf:eventForm.correctionOf||undefined,confirmed:true});await loadProject(project);setSelected(joints.find((joint)=>joint.id===selected.id)??selected);setConfirmed(false);setEventForm((previous)=>({...previous,occurredAt:isoNow(),remarks:"",inspectionReference:"",inspectionResult:"",reason:"",correctionOf:""}));setNotice("Event added to the append-only joint history.");}catch(e){setError(e instanceof Error?e.message:"Event could not be saved.");}finally{setSaving(false);}}
  async function saveStageConfig(){if(!workspace.organization||!project)return;const stages=stagesDraft.split("\n").map((stage)=>stage.trim()).filter(Boolean);if(stages.length<2||new Set(stages).size!==stages.length){setError("Configure at least two unique stages, one per line.");return;}let allowedTransitions:Record<string,string[]>;let stagePrerequisites:Record<string,string[]>;try{allowedTransitions=JSON.parse(transitionsDraft);stagePrerequisites=JSON.parse(prerequisitesDraft);if(Object.entries(allowedTransitions).some(([stage,next])=>!stages.includes(stage)||!Array.isArray(next)||next.some((value)=>!stages.includes(value)))||Object.entries(stagePrerequisites).some(([stage,required])=>!stages.includes(stage)||!Array.isArray(required)||required.some((value)=>!stages.includes(value))))throw new Error("Stage configuration refers to an unknown stage.");}catch(e){setError(e instanceof Error?`Check the transition/prerequisite JSON: ${e.message}`:"Transition or prerequisite JSON is invalid.");return;}try{await updateProjectSettings(workspace.organization.id,project.id,{stages,allowedTransitions,stagePrerequisites});const updated={...project,stages,allowedTransitions,stagePrerequisites};setProject(updated);setEventForm((previous)=>({...previous,stage:stages[0]}));setProjects((existing)=>existing.map((item)=>item.id===project.id?updated:item));setConfigOpen(false);setNotice("Stages, transitions, and prerequisites saved. Out-of-sequence events need a reason.");}catch(e){setError(e instanceof Error?e.message:"Stage configuration could not be saved.");}}
  function exportCsv(){if(!project)return;const from=windowStart?new Date(`${windowStart}T00:00:00`):undefined;const to=windowEnd?new Date(`${windowEnd}T23:59:59`):undefined;const windowEvents=events.filter((entry)=>{const date=new Date(entry.occurredAt);return(!from||date>=from)&&(!to||date<=to);});const rows:unknown[][]=[["Project",project.name],["Line",project.lineNumber],["Drawing",project.drawingNumber],["Revision",project.revision],["Event window",`${windowStart||"all"} to ${windowEnd||"all"}`],["Exported at",new Date().toISOString()],[],["JOINT REGISTER"],["Joint ID","Page","X normalized","Y normalized","Type","Weld type","Size","Material","Spool","Latest stage","Recorder","Event time","NDT result"],...joints.map((joint)=>{const last=progress.latestByJoint.get(joint.jointId??joint.id);return[joint.jointId??joint.id,joint.drawingPage??"",joint.x??"",joint.y??"",asText(joint.attributes?.jointType),asText(joint.attributes?.weldType),asText(joint.attributes?.size),asText(joint.attributes?.material),asText(joint.attributes?.spool),last?.stage??"Needs review",last?.recorderName??"",last?new Date(last.occurredAt).toISOString():"",last?.inspectionResult??""];}),[],["EVENT HISTORY IN SELECTED WINDOW"],["Joint ID","Stage","Event date/time","Recorded by","Crew","Welder","WPS","Inspection ref","Inspection result","Remarks","Correction reason"] ,...windowEvents.map((entry)=>[entry.jointId,entry.stage,new Date(entry.occurredAt).toISOString(),entry.recorderName,entry.crew??"",entry.welder??"",entry.wps??"",entry.inspectionReference??"",entry.inspectionResult??"",entry.remarks??"",entry.reason??""])];const cell=(v:unknown)=>`"${String(v??"").replace(/"/g,'""')}"`;const blob=new Blob(["\uFEFF",rows.map((row)=>row.map(cell).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"});const anchor=document.createElement("a");anchor.href=URL.createObjectURL(blob);anchor.download=`${project.drawingNumber}-${project.revision}-field-progress.csv`;anchor.click();URL.revokeObjectURL(anchor.href);}

  if(!workspace.user)return <Panel><h1 className="text-xl font-semibold">Sign in to Field Progress</h1><p className="mt-2 text-sm">Field records belong to an EPCX organization and require an authenticated member account.</p><a className="mt-4 inline-flex min-h-11 items-center bg-[#0e5549] px-4 text-sm font-semibold text-white" href="/login">Sign in</a></Panel>;
  if(!workspace.organization)return <Panel><h1 className="text-xl font-semibold">Field Progress</h1><p className="mt-2 text-sm">Join or select an EPCX organization to work with private, organization-scoped field records.</p>{workspace.loading?<p className="mt-3 text-xs">Loading organizationsâ€¦</p>:<p className="mt-3 text-xs">{workspace.error||"No organization membership is available on this account."}</p>}</Panel>;
  return <div className="space-y-4 text-slate-900 dark:text-white">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-accent-600">Field Progress / {workspace.organization.name}</p><h1 className="mt-1 text-2xl font-bold">Joint map and event register</h1><p className="mt-1 max-w-2xl text-sm text-slate-500">Open drawing â†’ select joint â†’ record a confirmed event â†’ review progress. Markup colors do not create events.</p></div>{isEditor&&<button onClick={()=>{setCreating(!creating);setProject(null);}} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-accent-600 px-4 text-sm font-semibold text-white"><Plus size={17}/>New work package</button>}</header>
    {(error||notice)&&<div role={error?"alert":"status"} className={`rounded-lg border px-4 py-3 text-sm ${error?"border-red-300 bg-red-50 text-red-800":"border-emerald-300 bg-emerald-50 text-emerald-800"}`}>{error||notice}<button onClick={()=>{setError("");setNotice("");}} className="float-right" aria-label="Dismiss">Ã—</button></div>}
    {workspace.organizations.length>1&&<label className="block max-w-sm text-xs font-semibold">Organization<select className="mt-1 block min-h-10 w-full rounded border bg-white px-2 dark:bg-slate-900" value={workspace.organization.id} onChange={(e)=>workspace.selectOrganization(e.target.value)}>{workspace.organizations.map((org)=><option key={org.id} value={org.id}>{org.name}</option>)}</select></label>}
    {workspace.organization.adminIds?.includes(workspace.user.uid)&&<section className="rounded-lg border bg-white p-3 dark:bg-brand-900"><button onClick={()=>{setEditorsDraft(workspace.organization?.fieldProgressEditorIds??[]);setAccessOpen(!accessOpen);}} className="text-xs font-semibold">Manage Field Progress editor access</button>{accessOpen&&<div className="mt-3 space-y-2">{[...new Set([...(workspace.organization.memberIds??[]),...(workspace.organization.adminIds??[])])].map((uid)=>{const admin=workspace.organization!.adminIds.includes(uid);const checked=admin||editorsDraft.includes(uid);return <label key={uid} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={checked} disabled={admin} onChange={(e)=>setEditorsDraft((old)=>e.target.checked?[...new Set([...old,uid])]:old.filter((item)=>item!==uid))}/><span className="font-mono">{uid}</span><span className="text-slate-500">{admin?"Admin":checked?"Editor":"Read only"}</span></label>;})}<button onClick={async()=>{try{await updateFieldProgressEditors(workspace.organization!.id,editorsDraft);await workspace.refreshOrganizations();setNotice("Field Progress editor access updated.");setAccessOpen(false);}catch(e){setError(e instanceof Error?e.message:"Editor access could not be updated.");}}} className="min-h-9 rounded bg-accent-600 px-3 text-xs font-semibold text-white">Save access</button></div>}</section>}
    {!isEditor&&<p className="rounded border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">You can view this organizationâ€™s Field Progress records. Ask an administrator to grant Field Progress editor access to record data.</p>}
    {creating&&<form onSubmit={(event)=>void createProject(event)} className="grid gap-3 rounded-xl border bg-white p-4 dark:bg-brand-900 md:grid-cols-3"><h2 className="font-semibold md:col-span-3">Create a work package and upload its drawing (PDF)</h2>{([...["name","lineNumber","drawingNumber","revision","areaSystem","workPackage"]] as string[]).map((key)=><label key={key} className="text-xs font-semibold capitalize">{key.replace(/([A-Z])/g," $1")}<input required={key!=="workPackage"} className="mt-1 block min-h-10 w-full rounded border px-2 text-sm dark:bg-slate-900" value={projectForm[key as keyof typeof projectForm]} onChange={(e)=>setProjectForm((old)=>({...old,[key]:e.target.value}))}/></label>)}<label className="text-xs font-semibold md:col-span-2">Isometric / weld map drawing (PDF only)<input required type="file" accept="application/pdf,.pdf" className="mt-1 block w-full text-sm" onChange={(e)=>setDrawingFile(e.target.files?.[0]??null)}/><span className="font-normal text-slate-500">Private to this organization. Keep the revision visible in the title block.</span></label><div className="flex items-end justify-end gap-2"><button type="button" onClick={()=>setCreating(false)} className="min-h-10 px-3 text-sm">Cancel</button><button disabled={saving||!isEditor||!drawingFile} className="min-h-10 rounded bg-accent-600 px-4 text-sm font-semibold text-white disabled:opacity-50">{saving?"Uploadingâ€¦":"Create project"}</button></div></form>}
    <div className="grid gap-4 xl:grid-cols-[300px_1fr]"><aside className="rounded-xl border bg-white dark:bg-brand-900"><div className="flex items-center justify-between border-b p-3"><h2 className="font-semibold">Work packages</h2><button onClick={()=>void reload()} aria-label="Refresh work packages" className="p-2"><RefreshCw size={15}/></button></div>{loading&&!project&&<p className="p-4 text-sm">Loadingâ€¦</p>}{projects.length===0&&!loading&&<p className="p-4 text-sm text-slate-500">No Field Progress work packages yet.</p>}<div className="divide-y">{projects.map((item)=><button key={item.id} onClick={()=>void loadProject(item)} className={`block w-full p-3 text-left hover:bg-slate-50 dark:hover:bg-slate-800 ${project?.id===item.id?"bg-emerald-50 dark:bg-emerald-950/30":""}`}><span className="block font-semibold">{item.name}</span><span className="mt-1 block text-xs text-slate-500">{item.lineNumber} Â· {item.drawingNumber} Â· Rev {item.revision}</span><span className="mt-1 block text-[10px] text-slate-500">{item.areaSystem}{item.workPackage?` Â· ${item.workPackage}`:""}</span></button>)}</div></aside>
      {!project?<div className="flex min-h-72 flex-col items-center justify-center rounded-xl border border-dashed p-8 text-center"><Wrench size={30} className="text-accent-600"/><p className="mt-3 font-semibold">Select a work package</p><p className="mt-1 max-w-md text-sm text-slate-500">Joint data and drawings are kept within the selected organization.</p></div>:<main className="min-w-0 space-y-4">
        <section className="rounded-xl border bg-white p-4 dark:bg-brand-900"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-accent-600">Current drawing revision</p><h2 className="mt-1 text-lg font-semibold">{project.drawingNumber} Â· Rev {project.revision}</h2><p className="text-xs text-slate-500">{project.lineNumber} Â· {project.areaSystem} {project.workPackage&&`Â· ${project.workPackage}`}</p></div><div className="flex flex-wrap gap-2"><label className="inline-flex min-h-10 cursor-pointer items-center gap-2 rounded border px-3 text-xs font-semibold"><FileSpreadsheet size={15}/>Import CSV/XLSX<input type="file" accept=".csv,.xlsx" className="sr-only" onChange={(e)=>void handleImport(e.target.files?.[0])}/></label>{isEditor&&<button onClick={()=>setShowJointForm(!showJointForm)} className="inline-flex min-h-10 items-center gap-2 rounded border px-3 text-xs font-semibold"><CirclePlus size={15}/>Add joint</button>}<button onClick={exportCsv} disabled={!joints.length} className="inline-flex min-h-10 items-center gap-2 rounded border px-3 text-xs font-semibold disabled:opacity-50"><ArrowDownToLine size={15}/>Export CSV</button>{isEditor&&<button onClick={()=>{setStagesDraft(project.stages.join("\n"));setTransitionsDraft(JSON.stringify(project.allowedTransitions,null,2));setPrerequisitesDraft(JSON.stringify(project.stagePrerequisites??{},null,2));setConfigOpen(!configOpen);}} className="inline-flex min-h-10 items-center gap-2 rounded border px-3 text-xs font-semibold"><Settings2 size={15}/>Stages</button>}</div></div>
          {newerRevisions.length>0&&<p className="mt-3 flex items-center gap-2 rounded border border-amber-300 bg-amber-50 p-2 text-xs text-amber-900"><AlertTriangle size={15}/>A newer revision ({newerRevisions.join(", ")}) is recorded in this organization. Confirm this revision before adding map pins.</p>}
          {configOpen&&<div className="mt-4 grid gap-3 border-t pt-4 md:grid-cols-2"><label className="text-xs font-semibold">Project stages — one per line<textarea rows={8} value={stagesDraft} onChange={(e)=>setStagesDraft(e.target.value)} className="mt-1 block w-full rounded border p-2 font-normal dark:bg-slate-900"/><span className="font-normal text-slate-500">Rename, hide, or reorder stages. Set transitions and prerequisites for this project.</span></label><label className="text-xs font-semibold">Allowed transitions (JSON object)<textarea rows={8} value={transitionsDraft} onChange={(e)=>setTransitionsDraft(e.target.value)} className="mt-1 block w-full rounded border p-2 font-mono text-[10px] font-normal dark:bg-slate-900"/><span className="font-normal text-slate-500">Example: {`{"Planned":["Fit-up complete"]}`}. Other stage changes need a reason.</span></label><label className="text-xs font-semibold md:col-span-2">Stage prerequisites (JSON object)<textarea rows={4} value={prerequisitesDraft} onChange={(e)=>setPrerequisitesDraft(e.target.value)} className="mt-1 block w-full rounded border p-2 font-mono text-[10px] font-normal dark:bg-slate-900"/><span className="font-normal text-slate-500">Defaults: Accepted requires Visual examination and NDT complete; Released requires Accepted. Checks use active joint history.</span></label><button onClick={()=>void saveStageConfig()} className="min-h-10 justify-self-end rounded bg-accent-600 px-4 py-2 text-sm font-semibold text-white">Save workflow settings</button></div>}
          {showJointForm&&<form onSubmit={(event)=>void createJoint(event)} className="mt-4 grid gap-2 border-t pt-4 sm:grid-cols-3"><h3 className="font-semibold sm:col-span-3">Register a joint (does not record progress)</h3>{Object.keys(jointForm).map((key)=><label key={key} className="text-xs capitalize">{key.replace(/([A-Z])/g," $1")}<input required={key==="id"} value={jointForm[key as keyof typeof jointForm]} onChange={(e)=>setJointForm((old)=>({...old,[key]:e.target.value}))} className="mt-1 block min-h-10 w-full rounded border px-2 dark:bg-slate-900"/></label>)}<button disabled={saving} className="min-h-10 rounded bg-accent-600 px-4 text-sm font-semibold text-white">Add joint</button></form>}
        </section>
        <div className="flex flex-wrap items-end gap-3"><label className="text-[10px] font-semibold">Events from<input type="date" value={windowStart} onChange={(e)=>setWindowStart(e.target.value)} className="mt-1 block min-h-9 rounded border px-2 text-xs dark:bg-slate-900"/></label><label className="text-[10px] font-semibold">through<input type="date" value={windowEnd} onChange={(e)=>setWindowEnd(e.target.value)} className="mt-1 block min-h-9 rounded border px-2 text-xs dark:bg-slate-900"/></label><button onClick={()=>{setWindowStart("");setWindowEnd("");}} className="min-h-9 rounded border px-3 text-xs">All dates</button></div>
        <section className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7">{[["Registered",progress.total],["Welded / period",progress.weldedInWindow],["NDT recorded",progress.ndtCompleted],["Repair",progress.repairs],["Re-exam",progress.reExaminations],["Accepted",progress.accepted],["Released",progress.released],["Remaining",progress.remaining]].map(([label,value])=><div key={String(label)} className="rounded-lg border bg-white p-3 dark:bg-brand-900"><p className="text-[10px] text-slate-500">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>)}</section><p className="-mt-2 text-[10px] text-slate-500">Registered, Accepted, Remaining, and latest-status counts use recorded project history. Welded, NDT recorded, Repair, and Re-exam count saved events in the selected date window. “Needs review” means a joint has no active event. Latest-state counts: {Object.entries(progress.statusCounts).map(([stage,count])=>`${stage}: ${count}`).join(" · ")||"No registered joints yet"}.</p>
        <div aria-label="Drawing pin status legend" className="flex flex-wrap gap-3 text-[10px] text-slate-600"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-emerald-700"/>Accepted/released</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-amber-500"/>Event recorded</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-slate-600"/>Needs review</span><span>Pins use normalized source-page coordinates and follow drawing zoom.</span></div><div className="grid min-w-0 gap-4 2xl:grid-cols-[1.1fr_.9fr]"><section className="min-w-0 overflow-hidden rounded-xl border bg-white dark:bg-brand-900"><div className="flex flex-wrap items-center justify-between gap-2 border-b p-3"><div><h3 className="font-semibold">Drawing map</h3><p className="text-[10px] text-slate-500">Rev {project.revision} Â· pins show recorded latest stages. Markups require a supervisor event.</p></div>{selected&&isEditor&&<button onClick={()=>setPinMode(!pinMode)} className={`min-h-10 rounded px-3 text-xs font-semibold ${pinMode?"bg-amber-600 text-white":"border"}`}>{pinMode?`Tap map to pin ${selected.jointId??selected.id}`:"Pin selected joint"}</button>}</div>{pdfUrl?<PdfDrawingViewer source={pdfUrl} drawingNumber={project.drawingNumber} revision={project.revision} joints={joints} latest={progress.latestByJoint} selectedPage={selected?.drawingPage} pinMode={pinMode} onSelect={setSelected} onPin={(x,y,page)=>void savePin(x,y,page)}/>:<p className="p-6 text-sm text-slate-500">No drawing is attached to this work package.</p>}<div className="flex justify-between border-t p-3 text-xs"><a className="underline" href={pdfUrl||undefined} target="_blank" rel="noreferrer">Open source PDF</a><span className="text-slate-500">Unsupported viewer? Select a joint in the register, then use manual location fields below.</span></div>
          <div className="max-h-60 overflow-auto border-t p-3"><div className="mb-2 flex items-center gap-2"><Search size={15}/><input aria-label="Search joint register" value={queryText} onChange={(e)=>setQueryText(e.target.value)} placeholder="Find joint ID, spool, materialâ€¦" className="min-h-9 w-full border px-2 text-xs dark:bg-slate-900"/></div><div className="divide-y">{filtered.map((joint)=>{const stage=progress.latestByJoint.get(joint.jointId??joint.id)?.stage??"Needs review";return <button key={joint.id} onClick={()=>setSelected(joint)} className={`grid w-full grid-cols-[1fr_auto] gap-2 py-2 text-left text-xs ${selected?.id===joint.id?"bg-emerald-50 dark:bg-emerald-950/30":""}`}><span className="font-semibold">{joint.jointId??joint.id}<span className="ml-2 font-normal text-slate-500">{asText(joint.attributes?.spool)} Â· {asText(joint.attributes?.size)}</span></span><span className="text-slate-600">{stage}</span></button>;})}{filtered.length===0&&<p className="py-3 text-xs text-slate-500">No joints registered. Add one or import CSV/XLSX.</p>}</div></div>
          {selected&&isEditor&&<div className="grid gap-2 border-t p-3 sm:grid-cols-3"><p className="text-xs font-semibold sm:col-span-3">Selected {selected.id} Â· map coordinate {(selected.x===undefined||selected.y===undefined)?"not pinned":`${(selected.x*100).toFixed(1)}%, ${(selected.y*100).toFixed(1)}%`}</p><label className="text-xs">Map X (%)<input type="number" min="0" max="100" step="0.1" value={selected.x===undefined?"":(selected.x*100).toFixed(1)} onChange={(e)=>setSelected({...selected,x:Number(e.target.value)/100})} className="mt-1 block min-h-9 w-full rounded border px-2 dark:bg-slate-900"/></label><label className="text-xs">Map Y (%)<input type="number" min="0" max="100" step="0.1" value={selected.y===undefined?"":(selected.y*100).toFixed(1)} onChange={(e)=>setSelected({...selected,y:Number(e.target.value)/100})} className="mt-1 block min-h-9 w-full rounded border px-2 dark:bg-slate-900"/></label><button onClick={async()=>{if(selected.x!==undefined&&selected.y!==undefined){await updateJointPin(workspace.organization!.id,project.id,{id:selected.jointId??selected.id,x:selected.x,y:selected.y,drawingPage:selected.drawingPage??1});await loadProject(project);}}} className="self-end rounded border px-3 py-2 text-xs">Save location</button></div>}
        </section><section className="min-w-0 space-y-3"><div className="rounded-xl border bg-white p-4 dark:bg-brand-900"><h3 className="font-semibold">Selected joint and event history</h3>{!selected?<p className="mt-2 text-sm text-slate-500">Choose a joint from the map or register.</p>:<><div className="mt-2 flex items-center justify-between"><p className="font-semibold">{selected.jointId??selected.id} Â· {progress.latestByJoint.get(selected.jointId??selected.id)?.stage??"Needs review"}</p><button onClick={async()=>{const history=await listJointEvents(workspace.organization!.id,project.id,selected.jointId??selected.id);setNotice(`${history.length} events in this joint history.`);}} className="text-xs underline">Refresh history</button></div><div className="mt-3 max-h-52 space-y-2 overflow-auto">{events.filter((entry)=>entry.jointId===(selected.jointId??selected.id)).map((entry)=><article key={entry.id} className="border-l-2 border-accent-600 bg-slate-50 p-2 text-xs dark:bg-slate-800"><p className="font-semibold">{entry.stage} Â· {new Date(entry.occurredAt).toLocaleString()}</p><p>Recorded by {entry.recorderName}</p>{entry.remarks&&<p>{entry.remarks}</p>}{entry.inspectionResult&&<p>Inspection: {entry.inspectionResult} {entry.inspectionReference&&`Â· ${entry.inspectionReference}`}</p>}{entry.correctionOf&&<p>Corrects prior event {entry.correctionOf.slice(0,8)}.</p>}{entry.reason&&<p>Reason/correction: {entry.reason}</p>}</article>)}{events.filter((entry)=>entry.jointId===(selected.jointId??selected.id)).length===0&&<p className="text-xs text-slate-500">No field events. A joint registration or drawing color is not progress.</p>}</div>
            {isEditor&&<form onSubmit={(event)=>void saveEvent(event)} className="mt-4 space-y-2 border-t pt-3"><h4 className="text-sm font-semibold">Record a new field event</h4><label className="block text-xs">Stage<select required value={eventForm.stage} onChange={(e)=>setEventForm({...eventForm,stage:e.target.value})} className="mt-1 min-h-10 w-full rounded border px-2 dark:bg-slate-900">{project.stages.map((stage)=><option key={stage}>{stage}</option>)}</select></label><label className="block text-xs">Event date/time<input required type="datetime-local" value={eventForm.occurredAt} onChange={(e)=>setEventForm({...eventForm,occurredAt:e.target.value})} className="mt-1 min-h-10 w-full rounded border px-2 dark:bg-slate-900"/></label><label className="block text-xs">Correct a prior event (optional)<select value={eventForm.correctionOf} onChange={(e)=>setEventForm({...eventForm,correctionOf:e.target.value})} className="mt-1 min-h-10 w-full rounded border px-2 dark:bg-slate-900"><option value="">New event</option>{events.filter((entry)=>entry.jointId===(selected.jointId??selected.id)).map((entry)=><option key={entry.id} value={entry.id}>{entry.stage} Â· {new Date(entry.occurredAt).toLocaleString()}</option>)}</select></label><div className="grid grid-cols-2 gap-2">{(["crew","welder","wps","inspectionReference","remarks","reason"] as const).map((field)=><label key={field} className="text-xs capitalize">{field.replace(/([A-Z])/g," $1")}<input value={eventForm[field]} onChange={(e)=>setEventForm({...eventForm,[field]:e.target.value})} className="mt-1 min-h-9 w-full rounded border px-2 dark:bg-slate-900"/></label>)}</div>{(eventForm.stage.toLowerCase().includes("ndt")||eventForm.inspectionReference)&&<label className="block text-xs">Inspection / NDT result<select value={eventForm.inspectionResult} onChange={(e)=>setEventForm({...eventForm,inspectionResult:e.target.value})} className="mt-1 min-h-10 w-full rounded border px-2 dark:bg-slate-900"><option value="">Select result</option><option>Pass</option><option>Fail</option><option>Pending</option></select></label>}<label className="flex items-start gap-2 text-xs"><input type="checkbox" checked={confirmed} onChange={(e)=>setConfirmed(e.target.checked)} className="mt-0.5"/>I confirm this event reflects field information I reviewed. It will be retained in the append-only event history.</label><button disabled={!confirmed||saving} className="min-h-11 w-full rounded bg-accent-600 px-3 text-sm font-semibold text-white disabled:opacity-50">{saving?"Savingâ€¦":"Confirm and record event"}</button></form>}</>}</div></section></div>
      </main>}
    </div>
  </div>;
}

function Panel({children}:{children:React.ReactNode}){return <div className="mx-auto mt-10 max-w-3xl rounded-xl border bg-white p-6 text-slate-800 dark:bg-brand-900 dark:text-white">{children}</div>}








