"use client";

import { useEffect, useState, type FormEvent } from "react";
import { Building2, Plus, Users } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { useProjectWorkspace } from "@/contexts/ProjectWorkspaceContext";
import { listUserOrganizations } from "@/lib/billcheck/data";
import { createOrganization, saveProfessionalProfile } from "@/lib/firebase/firestore";
import type { Organization } from "@/types/firebase";

const input = "w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-900 outline-none focus:border-accent-500 dark:border-slate-700 dark:bg-slate-800 dark:text-white";
export default function OrganizationPage() {
  const { user } = useAuth(); const { projects, refreshProjects } = useProjectWorkspace();
  const [organizations, setOrganizations] = useState<Organization[]>([]); const [creating, setCreating] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const [name, setName] = useState(""); const [details, setDetails] = useState(""); const [logoURL, setLogoURL] = useState("");
  useEffect(() => { if (user) void listUserOrganizations(user.uid).then(setOrganizations).catch((error) => setMessage(error instanceof Error ? error.message : "Organization could not load.")); }, [user]);
  async function create(event: FormEvent) { event.preventDefault(); if (!user || !name.trim()) return; setBusy(true); setMessage(""); try { const organization = await createOrganization({ name, companyDetails: details, logoURL, uid: user.uid }); await saveProfessionalProfile(user.uid, { uid: user.uid, displayName: user.displayName ?? "", email: user.email ?? "", photoURL: user.photoURL ?? undefined, organizationId: organization.id, role: "engineer" }); setOrganizations(await listUserOrganizations(user.uid)); await refreshProjects(); setCreating(false); setMessage("Organization created and connected to your profile."); } catch (error) { setMessage(error instanceof Error ? error.message : "Organization could not be created."); } finally { setBusy(false); } }
  return <div className="mx-auto max-w-4xl space-y-7">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-accent-600">Administration</p><h1 className="mt-2 font-display text-3xl font-bold text-slate-900 dark:text-white">Organization</h1><p className="mt-1 text-sm text-slate-500">Keep your company identity alongside its project sites.</p></div>{organizations.length === 0 && <button onClick={() => setCreating(true)} className="flex items-center gap-2 rounded-xl bg-accent-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4" /> Create organization</button>}</header>
    {message && <p role="status" className="text-sm text-slate-600 dark:text-slate-300">{message}</p>}
    {creating && <form onSubmit={create} className="space-y-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-card dark:border-slate-800 dark:bg-brand-900"><div><h2 className="font-semibold text-slate-900 dark:text-white">Create your organization</h2><p className="mt-1 text-xs text-slate-500">You can do this later; project setup does not depend on it.</p></div><label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-500">Organization name *</span><input required className={input} value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. PEC" /></label><label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-500">Company details</span><textarea className={input} rows={3} value={details} onChange={(e) => setDetails(e.target.value)} placeholder="Company information" /></label><label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-500">Logo URL (optional)</span><input className={input} type="url" value={logoURL} onChange={(e) => setLogoURL(e.target.value)} placeholder="https://…" /></label><div className="flex justify-end gap-2"><button type="button" onClick={() => setCreating(false)} className="rounded-xl px-4 py-2 text-sm text-slate-500">Cancel</button><button disabled={busy} className="rounded-xl bg-accent-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{busy ? "Creating…" : "Create organization"}</button></div></form>}
    {organizations.map((organization) => { const orgProjects = projects.filter((project) => project.organizationId === organization.id); return <article key={organization.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-card dark:border-slate-800 dark:bg-brand-900"><div className="flex items-center gap-4">{organization.logoURL ? <img src={organization.logoURL} alt="" className="h-12 w-12 rounded-xl object-contain" /> : <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-accent-500/10 text-accent-700"><Building2 className="h-6 w-6" /></div>}<div><h2 className="font-display text-xl font-bold text-slate-900 dark:text-white">{organization.name}</h2><p className="text-sm text-slate-500">Organization workspace</p></div></div>{organization.companyDetails && <p className="mt-4 max-w-2xl text-sm text-slate-600 dark:text-slate-300">{organization.companyDetails}</p>}<div className="mt-5 flex gap-6 border-t border-slate-100 pt-4 dark:border-slate-800"><div><p className="flex items-center gap-1.5 text-lg font-bold text-slate-900 dark:text-white"><Users className="h-4 w-4 text-accent-600" />{organization.memberIds?.length ?? organization.adminIds?.length ?? 1}</p><p className="text-xs text-slate-500">members</p></div><div><p className="text-lg font-bold text-slate-900 dark:text-white">{orgProjects.length}</p><p className="text-xs text-slate-500">active projects</p></div></div></article>; })}
    {organizations.length > 0 && <p className="text-xs text-slate-500">To add or manage projects, use <a href="/projects" className="font-semibold text-accent-700">Projects / sites</a>. Team invitations are managed inside each project.</p>}
  </div>;
}
